FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json ./
COPY tsconfig.json tsconfig.app.json tsconfig.node.json vite.config.ts vite.config.js ./
RUN npm install

COPY index.html ./
COPY src ./src

RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
